# Matrix-powers tuning variants.
#
# Generated by scripts/regime/ca_matrix_powers_configurations.py.  Edit that
# script and regenerate rather than editing this file: the same table produces
# data/ca-matrix-powers-tuning/configurations.csv, which records why every
# rejected shape was excluded, and the two have to agree.
#
# Every entry below passed the pre-build filters in section 5.3 of the
# specification: the shared-memory volumes fit at at least one screened width,
# the interior volume is at least the thread count, work per thread is within
# the first-screen limit, and the grid supplies at least two waves at the
# production grids. A width a shape cannot hold is reported by the harness as
# not admissible and recorded as such, so it costs a row rather than the shape.
#
# The two baselines are absent on purpose: ca-matrix-powers is built on every
# default and is already the full-volume and plane-streamed baseline at once.

caksm_add_matrix_powers_variant(
        NAME 8x8x8
        FAMILY full-volume
        TILE_X 8
        TILE_Y 8
        TILE_Z 8
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME 16x8x4
        FAMILY full-volume
        TILE_X 16
        TILE_Y 8
        TILE_Z 4
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME 16x8x8
        FAMILY full-volume
        TILE_X 16
        TILE_Y 8
        TILE_Z 8
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME 12x8x8
        FAMILY full-volume
        TILE_X 12
        TILE_Y 8
        TILE_Z 8
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME 20x8x4
        FAMILY full-volume
        TILE_X 20
        TILE_Y 8
        TILE_Z 4
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME 24x8x4
        FAMILY full-volume
        TILE_X 24
        TILE_Y 8
        TILE_Z 4
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME 24x4x4
        FAMILY full-volume
        TILE_X 24
        TILE_Y 4
        TILE_Z 4
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME 32x4x4
        FAMILY full-volume
        TILE_X 32
        TILE_Y 4
        TILE_Z 4
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME 16x12x4
        FAMILY full-volume
        TILE_X 16
        TILE_Y 12
        TILE_Z 4
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME 16x4x12
        FAMILY full-volume
        TILE_X 16
        TILE_Y 4
        TILE_Z 12
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME 8x16x4
        FAMILY full-volume
        TILE_X 8
        TILE_Y 16
        TILE_Z 4
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME 8x4x16
        FAMILY full-volume
        TILE_X 8
        TILE_Y 4
        TILE_Z 16
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME 10x12x16
        FAMILY full-volume
        TILE_X 10
        TILE_Y 12
        TILE_Z 16
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME 10x16x12
        FAMILY full-volume
        TILE_X 10
        TILE_Y 16
        TILE_Z 12
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME 12x12x12
        FAMILY full-volume
        TILE_X 12
        TILE_Y 12
        TILE_Z 12
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME 20x12x8
        FAMILY full-volume
        TILE_X 20
        TILE_Y 12
        TILE_Z 8
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME 20x8x12
        FAMILY full-volume
        TILE_X 20
        TILE_Y 8
        TILE_Z 12
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME 18x12x8
        FAMILY full-volume
        TILE_X 18
        TILE_Y 12
        TILE_Z 8
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME 18x8x12
        FAMILY full-volume
        TILE_X 18
        TILE_Y 8
        TILE_Z 12
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME stream-8x8-t64
        FAMILY plane-streamed
        TILE_X 8
        TILE_Y 8
        THREADS 64)

caksm_add_matrix_powers_variant(
        NAME stream-32x16
        FAMILY plane-streamed
        TILE_X 32
        TILE_Y 16
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME stream-24x16
        FAMILY plane-streamed
        TILE_X 24
        TILE_Y 16
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME stream-32x12
        FAMILY plane-streamed
        TILE_X 32
        TILE_Y 12
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME stream-24x12
        FAMILY plane-streamed
        TILE_X 24
        TILE_Y 12
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME stream-16x16
        FAMILY plane-streamed
        TILE_X 16
        TILE_Y 16
        THREADS 128)

caksm_add_matrix_powers_variant(
        NAME stream-16x12
        FAMILY plane-streamed
        TILE_X 16
        TILE_Y 12
        THREADS 128)
